version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Nothing to do in install phase"
      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker version || exit 1
      - echo "Cleaning Docker builder cache..."
      - docker builder prune -f

      - echo "Cleaning old Docker images to free up space..."
      - docker image prune -f

  build:
    commands:
      - echo "Build started on $(date)"

      - echo "Downloading environment file from S3..."
      - aws s3 cp "s3://buildxup-delopyment-stage/backend/.env" .

      - echo "Exporting env variables from .env..."
      - export $(cat .env | grep -v '^#' | xargs)

      - echo "Installing NPM dependencies..."
      - npm ci

      - echo "Generating Prisma client..."
      - npm run prisma:all:generate

      - echo "Running build to generate dist/"
      - export NODE_OPTIONS="--max_old_space_size=4096"
      - npm run build

      - echo "Preparing Docker image for Lambda..."
      # - export IMAGE_TAG=$(date +%s)
      - export ECR_REPO="stage/buildxup/backend"
      - export IMAGE_URI="530061243896.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPO:latest"

      - echo "Logging into ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 530061243896.dkr.ecr.us-east-1.amazonaws.com

      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .

      - echo "Pushing Docker image to ECR..."
      - docker push $IMAGE_URI

      - echo "Substituting env vars into SAM template..."
      - export IMAGE_URI=$IMAGE_URI
      - envsubst < template.yaml > template-processed.yaml

      - export ECR_REPO_URI="530061243896.dkr.ecr.us-east-1.amazonaws.com/stage/buildxup/backend"

      - echo "Packaging SAM template..."
      - |
        sam package \
          --template-file template-processed.yaml \
          --s3-bucket "buildxup-delopyment-stage" \
          --s3-prefix "backend" \
          --output-template-file "artifact.yaml"

      - echo "Checking artifact.yaml exists..."
      - ls -la artifact.yaml

      - echo "Build completed on $(date)"

artifacts:
  files:
    - template.yaml
    - template-processed.yaml
    - artifact.yaml
    - dist/**/*
