version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
      python: 3.11
    commands:
      - pip install aws-sam-cli
      - npm install
      - aws s3 cp s3://buildxup-delopyment-stage/backend/.env .env
  pre_build:
    commands:
      - echo "Running pre-build scripts"
  build:
    commands:
      - sam build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - template.yaml
    - .aws-sam/**
    - src/**
    - package.json
    - package-lock.json
    - .env
