AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BuildXup Backend API

Parameters:
  StageName:
    Type: String
    Default: stage


Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs22.x

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: StageName
      BinaryMediaTypes:
        - "*/*"
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./module_auth
      Handler: module_auth/handler.app
      Role: arn:aws:iam::530061243896:role/Lambda_Execution_Role
      Timeout: 60
      Events:
        Auth:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /auth/{proxy+}
            Method: ANY

  ProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./module_project
      Handler: module_project/handler.app
      Role: arn:aws:iam::530061243896:role/Lambda_Execution_Role
      Timeout: 30
      Events:
        Project:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /projects/{proxy+}
            Method: ANY

  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./module_task
      Handler: module_task/handler.app
      Role: arn:aws:iam::530061243896:role/Lambda_Execution_Role
      Timeout: 30
      Events:
        Task:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /tasks/{proxy+}
            Method: ANY

  EmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./module_employee
      Handler: module_employee/handler.app
      Role: arn:aws:iam::530061243896:role/Lambda_Execution_Role
      Timeout: 30
      Events:
        Employee:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /employees/{proxy+}
            Method: ANY

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: ping.handler
      Role: arn:aws:iam::530061243896:role/Lambda_Execution_Role
      Timeout: 30
      Events:
        Ping:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /server/ping
            Method: get
        PingDb:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /server/ping-db
            Method: get

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: 
      Fn::Sub: "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"